--- #YAML:1.0
name:               Tie-Quicksort-Lazy
version:            0.04
abstract:           a lazy quicksort with tiearray interface
author:
    - U-OFFICE\David <David@x-ray.at>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
